### ISSUE TITLE
Title extractor doesn't work

### ISSUE THREAD

**Issue by skyler-0** [johnpiapian/youtube-title-extractor#1]
```❯ python3 app.py PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q video_titles.xlsx
Traceback (most recent call last):
  File "/home/skyler/youtube-title-extractor/app.py", line 2, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
❯ pip install XlsxWriter
Defaulting to user installation because normal site-packages is not writeable
Collecting XlsxWriter
  Using cached XlsxWriter-3.1.1-py3-none-any.whl (152 kB)
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-3.1.1
❯ python3 app.py PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q video_titles.xlsx
Traceback (most recent call last):
  File "/home/skyler/youtube-title-extractor/app.py", line 3, in <module>
    import extract_title
  File "/home/skyler/youtube-title-extractor/extract_title.py", line 2, in <module>
    import constants
ModuleNotFoundError: No module named 'constants'
❯ touch constants.py
❯ python3 app.py PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q video_titles.xlsx
Traceback (most recent call last):
  File "/home/skyler/youtube-title-extractor/app.py", line 3, in <module>
    import extract_title
  File "/home/skyler/youtube-title-extractor/extract_title.py", line 3, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
```
that's the error message I got

**Comment by johnpiapian** [comment]
I have been making a few changes recently, so my guess would be that the instruction I have here is out dated. I will update the readme file accordingly, as soon as possible.

**Comment by johnpiapian** [comment]
I have updated the readme file so you should be able to follow it. If you merely want to use the app then you can visit https://appzomi.dev/dev/apps/youtube-title-extrator.
